-- Add diverse content submissions with various statuses
INSERT INTO content_submissions (
  campaign_id, 
  influencer_id, 
  platform, 
  content_type, 
  caption, 
  content_url, 
  status, 
  compliance_checked, 
  fec_disclosure, 
  review_notes,
  submission_date
) VALUES 
-- Pending submissions (4)
(
  (SELECT id FROM campaigns LIMIT 1 OFFSET 0),
  (SELECT id FROM influencers LIMIT 1 OFFSET 0),
  'Instagram',
  'post',
  'Ready to vote for real change! 🇺🇸 #VoteForChange #Election2024',
  'https://instagram.com/p/abc123',
  'pending',
  false,
  NULL,
  NULL,
  NOW() - INTERVAL '2 days'
),
(
  (SELECT id FROM campaigns LIMIT 1 OFFSET 1),
  (SELECT id FROM influencers LIMIT 1 OFFSET 1),
  'TikTok',
  'video',
  'Why your vote matters this election! Link in bio for voter registration 📊',
  'https://tiktok.com/@user/video/123',
  'pending',
  false,
  NULL,
  NULL,
  NOW() - INTERVAL '1 day'
),
(
  (SELECT id FROM campaigns LIMIT 1 OFFSET 2),
  (SELECT id FROM influencers LIMIT 1 OFFSET 2),
  'YouTube',
  'video',
  'Breaking down the candidates positions on healthcare policy',
  'https://youtube.com/watch?v=abc123',
  'pending',
  false,
  NULL,
  NULL,
  NOW() - INTERVAL '3 hours'
),
(
  (SELECT id FROM campaigns LIMIT 1 OFFSET 0),
  (SELECT id FROM influencers LIMIT 1 OFFSET 3),
  'Twitter',
  'post',
  'Just posted my voter guide! Check it out and share with friends 🗳️',
  'https://twitter.com/user/status/123',
  'pending',
  false,
  NULL,
  NULL,
  NOW() - INTERVAL '6 hours'
),
-- Revision requested submissions (3)
(
  (SELECT id FROM campaigns LIMIT 1 OFFSET 1),
  (SELECT id FROM influencers LIMIT 1 OFFSET 4),
  'Instagram',
  'story',
  'Vote for candidate X! They''re the best choice for America!',
  'https://instagram.com/stories/user/123',
  'revision_requested',
  false,
  NULL,
  'Missing required FEC disclosure statement. Please add "Paid for by [PAC Name]" to comply with campaign finance regulations.',
  NOW() - INTERVAL '5 days'
),
(
  (SELECT id FROM campaigns LIMIT 1 OFFSET 2),
  (SELECT id FROM influencers LIMIT 1 OFFSET 5),
  'Facebook',
  'post',
  'This candidate will fix everything wrong with our country!',
  'https://facebook.com/posts/123',
  'revision_requested',
  false,
  'Paid for by Future PAC',
  'Content contains unsubstantiated claims. Please provide factual information and avoid hyperbolic language per FEC guidelines.',
  NOW() - INTERVAL '4 days'
),
(
  (SELECT id FROM campaigns LIMIT 1 OFFSET 0),
  (SELECT id FROM influencers LIMIT 1 OFFSET 6),
  'TikTok',
  'video',
  'Here''s why you should vote! #sponsored #politics',
  'https://tiktok.com/@user/video/456',
  'revision_requested',
  false,
  NULL,
  'Hashtag #sponsored is insufficient for political content. Must include full FEC-compliant disclosure statement.',
  NOW() - INTERVAL '6 days'
),
-- Additional approved submissions (2)
(
  (SELECT id FROM campaigns LIMIT 1 OFFSET 1),
  (SELECT id FROM influencers LIMIT 1 OFFSET 7),
  'Instagram',
  'post',
  'Exercise your right to vote! Every voice matters in our democracy. 🗳️ Paid for by Future Forward PAC',
  'https://instagram.com/p/def456',
  'approved',
  true,
  'Paid for by Future Forward PAC',
  'Content approved - includes proper FEC disclosure and factual messaging.',
  NOW() - INTERVAL '1 week'
),
(
  (SELECT id FROM campaigns LIMIT 1 OFFSET 2),
  (SELECT id FROM influencers LIMIT 1 OFFSET 0),
  'YouTube',
  'video',
  'Understanding ballot measures in your area - nonpartisan voter education. Paid for by Civic Engagement PAC',
  'https://youtube.com/watch?v=ghi789',
  'approved',
  true,
  'Paid for by Civic Engagement PAC',
  'Educational content approved - maintains nonpartisan stance with proper disclosure.',
  NOW() - INTERVAL '10 days'
),
-- Mixed priority submissions (3)
(
  (SELECT id FROM campaigns LIMIT 1 OFFSET 0),
  (SELECT id FROM influencers LIMIT 1 OFFSET 1),
  'Twitter',
  'post',
  'Democracy works when we all participate! Register to vote today. Link: vote.gov',
  'https://twitter.com/user/status/789',
  'approved',
  true,
  'Paid for by Democracy First PAC',
  'Excellent civic engagement content with proper disclosure.',
  NOW() - INTERVAL '2 weeks'
),
(
  (SELECT id FROM campaigns LIMIT 1 OFFSET 1),
  (SELECT id FROM influencers LIMIT 1 OFFSET 2),
  'Instagram',
  'post',
  'Quick facts about candidate policies - swipe for sources!',
  'https://instagram.com/p/jkl012',
  'pending',
  false,
  NULL,
  NULL,
  NOW() - INTERVAL '8 hours'
),
(
  (SELECT id FROM campaigns LIMIT 1 OFFSET 2),
  (SELECT id FROM influencers LIMIT 1 OFFSET 3),
  'Facebook',
  'video',
  'Town hall highlights: What matters to our community',
  'https://facebook.com/videos/345',
  'approved',
  true,
  'Paid for by Community Voice PAC',
  'Community-focused content with appropriate disclosure.',
  NOW() - INTERVAL '3 weeks'
);